---
    environment: production-transformers
    chdir: /var/lib/admin_submarine/current
    address: ent
    user: administrator
    group: rvm
    port: 3010
    pid: /var/lib/admin_submarine/current/tmp/pids/thin.pid
    rackup: /var/lib/admin_submarine/current/config.ru
    log: /var/lib/admin_submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

