---
    environment: azubi_submarine
    chdir: /var/lib/azubi_submarine/current
    user: railsprod
    group: rvm
    port: 3012
    pid: /var/lib/azubi_submarine/current/tmp/pids/thin.pid
    rackup: /var/lib/azubi_submarine/current/config.ru
    log: /var/lib/azubi_submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

