---
    environment: production-ext
    chdir: /var/lib/submarine/current
    address: 0.0.0.0
    user: railsprod
    group: railsprod
    port: 3000
    pid: /var/lib/submarine/current/tmp/pids/thin.pid
    rackup: /var/lib/submarine/current/config.ru
    log: /var/lib/submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

