---
    environment: production
    chdir: /var/lib/submarine/current
    address: ent
    user: administrator
    group: administrator
    port: 3000
    pid: /var/lib/submarine/current/tmp/thin.pid
    rackup: /var/lib/submarine/current/config.ru
    log: /var/lib/submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
