---
    environment: seminar_submarine
    chdir: /var/lib/seminar_submarine/current
    address: SubSeminar
    user: railsprod
    group: rvm
    port: 3011
    pid: /var/lib/seminar_submarine/current/tmp/pids/thin.pid
    rackup: /var/lib/seminar_submarine/current/config.ru
    log: /var/lib/seminar_submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

