---
    environment: production-transformers
    chdir: /var/lib/transformers_submarine/current
    address: submarine-transformers
    user: railsprod
    group: rvm
    port: 3002
    pid: /var/lib/transformers_submarine/current/tmp/pids/thin.pid
    rackup: /var/lib/transformers_submarine/current/config.ru
    log: /var/lib/transformers_submarine/current/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true

